apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: {{ .Values.service.backendPort }}
