apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: {{ .Values.service.frontendPort }}
