apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
  selector:
    app: {{ .Values.applicationName }}-frontend
